---
version: 2

workflows:
  version: 2
  cc:
    jobs:
      - build
      - flatpak
      - appimage

jobs:
  build:
    working_directory: ~/work
    machine:
      image: ubuntu-1604:201903-01

    steps:
      #- checkout
      # circleCI checkout fix
      - run: wget "https://raw.githubusercontent.com/zoff99/ToxAndroidRefImpl/zoff99/dev003/.circleci/checkout_fix.sh" -O /tmp/c.sh
      - run: bash /tmp/c.sh

      - run: sudo pkill apt-get || echo dummy
      - run: apt --version
      - run: ls -al /etc/apt/sources.list.d/
      - run: sudo rm /etc/apt/sources.list.d/heroku.list
      - run: sudo rm /etc/apt/sources.list.d/google-chrome.list
      - run: sudo apt update &&
          sudo apt install -y --no-install-recommends apt apt-transport-https
      - run: apt --version
      - run: sudo apt update &&
          sudo apt install -y --no-install-recommends
            grep rsync xz-utils file git curl ssh
            openssl ca-certificates git sudo bc wget rsync
            binfmt-support unzip docker

      - run: ls -al ~/work
      - run: docker --version
      - run: cd ~/work/.localrun ; bash ./docker_it.sh

      - store_artifacts:
          path: ~/work/.localrun/alpine_3.12.0/artefacts
          destination: artefacts_alpine_3_12_0

      - store_artifacts:
          path: ~/work/.localrun/ubuntu_18.04/artefacts
          destination: artefacts_ubuntu_18_04

      - store_artifacts:
          path: ~/work/.localrun/debian_10/artefacts
          destination: artefacts_debian_10

      - store_artifacts:
          path: ~/work/.localrun/ubuntu_20.04/artefacts
          destination: artefacts_ubuntu_20_04

      - store_artifacts:
          path: ~/work/.localrun/debian_9/artefacts
          destination: artefacts_debian_9

      - store_artifacts:
          path: ~/work/.localrun/ubuntu_16.04/artefacts
          destination: artefacts_ubuntu_16_04


  flatpak:
    working_directory: ~/work
    machine:
      image: ubuntu-1604:201903-01
    steps:
      #- checkout
      # circleCI checkout fix
      - run: wget "https://raw.githubusercontent.com/zoff99/ToxAndroidRefImpl/zoff99/dev003/.circleci/checkout_fix.sh" -O /tmp/c.sh
      - run: bash /tmp/c.sh

      - run: sudo pkill apt-get || echo dummy
      - run: apt --version
      - run: ls -al /etc/apt/sources.list.d/
      - run: sudo rm /etc/apt/sources.list.d/heroku.list
      - run: sudo rm /etc/apt/sources.list.d/google-chrome.list
      - run: sudo apt update &&
          sudo apt install -y --no-install-recommends apt apt-transport-https
      - run: apt --version
      - run: sudo apt update &&
          sudo apt install -y --no-install-recommends
            grep rsync xz-utils file git curl ssh
            openssl ca-certificates git sudo bc wget rsync
            binfmt-support unzip docker

      - run: ls -al ~/work
      - run: docker --version
      - run: cd ~/work/.localrun ; bash ./flatpak_it.sh

      - store_artifacts:
          path: ~/work/.localrun/ubuntu_20.04_flatpak/artefacts
          destination: artefacts_flatpak


  appimage:
    working_directory: ~/work
    machine:
      image: ubuntu-1604:201903-01
    steps:
      #- checkout
      # circleCI checkout fix
      - run: wget "https://raw.githubusercontent.com/zoff99/ToxAndroidRefImpl/zoff99/dev003/.circleci/checkout_fix.sh" -O /tmp/c.sh
      - run: bash /tmp/c.sh

      - run: sudo pkill apt-get || echo dummy
      - run: apt --version
      - run: ls -al /etc/apt/sources.list.d/
      - run: sudo rm /etc/apt/sources.list.d/heroku.list
      - run: sudo rm /etc/apt/sources.list.d/google-chrome.list
      - run: sudo apt update &&
          sudo apt install -y --no-install-recommends apt apt-transport-https
      - run: apt --version
      - run: sudo apt update &&
          sudo apt install -y --no-install-recommends
            grep rsync xz-utils file git curl ssh
            openssl ca-certificates git sudo bc wget rsync
            binfmt-support unzip docker

      - run: ls -al ~/work
      - run: docker --version
      - run: cd ~/work/.localrun ; bash ./appimage_it.sh

      - store_artifacts:
          path: ~/work/.localrun/ubuntu_18.04_appimage/artefacts
          destination: artefacts_appimage_ubuntu_18_04

      - store_artifacts:
          path: ~/work/.localrun/ubuntu_16.04_appimage/artefacts
          destination: artefacts_appimage_ubuntu_16_04

