---
version: 2

workflows:
  version: 2
  cc:
    jobs:
      - build
      - flatpak
      - appimage

jobs:
  build:
    working_directory: ~/work
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout

      - run: sudo pkill apt-get || echo dummy
      - run: apt --version
      - run: ls -al /etc/apt/sources.list.d/
      - run: sudo rm /etc/apt/sources.list.d/heroku.list
      - run: sudo rm /etc/apt/sources.list.d/google-chrome.list
      - run: sudo apt update &&
          sudo apt install -y --no-install-recommends apt apt-transport-https
      - run: apt --version
      - run: sudo apt update &&
          sudo apt install -y --no-install-recommends
            grep rsync xz-utils file git curl ssh
            openssl ca-certificates git sudo bc wget rsync
            binfmt-support unzip docker

      - run: ls -al ~/work
      - run: docker --version
      - run: cd ~/work/.localrun ; bash ./docker_it.sh

jobs:
  flatpak:
    working_directory: ~/work
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout

      - run: sudo pkill apt-get || echo dummy
      - run: apt --version
      - run: ls -al /etc/apt/sources.list.d/
      - run: sudo rm /etc/apt/sources.list.d/heroku.list
      - run: sudo rm /etc/apt/sources.list.d/google-chrome.list
      - run: sudo apt update &&
          sudo apt install -y --no-install-recommends apt apt-transport-https
      - run: apt --version
      - run: sudo apt update &&
          sudo apt install -y --no-install-recommends
            grep rsync xz-utils file git curl ssh
            openssl ca-certificates git sudo bc wget rsync
            binfmt-support unzip docker

      - run: ls -al ~/work
      - run: docker --version
      - run: cd ~/work/.localrun ; bash ./flatpak_it.sh


jobs:
  appimage:
    working_directory: ~/work
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout

      - run: sudo pkill apt-get || echo dummy
      - run: apt --version
      - run: ls -al /etc/apt/sources.list.d/
      - run: sudo rm /etc/apt/sources.list.d/heroku.list
      - run: sudo rm /etc/apt/sources.list.d/google-chrome.list
      - run: sudo apt update &&
          sudo apt install -y --no-install-recommends apt apt-transport-https
      - run: apt --version
      - run: sudo apt update &&
          sudo apt install -y --no-install-recommends
            grep rsync xz-utils file git curl ssh
            openssl ca-certificates git sudo bc wget rsync
            binfmt-support unzip docker

      - run: ls -al ~/work
      - run: docker --version
      - run: cd ~/work/.localrun ; bash ./appimage_it.sh


